### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by spodermenpls** [spodermenpls/smartquotes#1]
@jobisoft Hast du schon einen Blick auf das Projekt werfen können, und vielleicht eine erste Einschätzung? 😏

**Comment by spodermenpls** [comment]
@jobisoft Thank you very much for your commit. The eggshells have cracked, so I've made the repo public.

I've replaced the old .png symbols with the newer ones introduced by Mr. Marc H. (presumably "MH" on thunderbird-mail.de/forum), which are a lot nicer than the original ones (which were only present in the "NewBuild" folder).

**Comment by kkapsner** [comment]
@jobisoft: can you help me to find the console of a composer window? I do not find anything in the UI and the typical keyboard shortcuts (F12, Ctrl+Shift+I, Ctrl+Shift+J, Ctrl+Shift+K) do not work either. Also in the debugging window of the addon the `console.log` messages do not appear - only error messages.

**Comment by jobisoft** [comment]
The composer does not have its own console, but it does consume the shortcuts, so nothing happens if you use CTRL+SHIFT+J in the composer. Open the console from the main window. 

To see all log entries, use the *hint* given here:
https://developer.thunderbird.net/add-ons/tips-and-tricks#debugging

**Comment by kkapsner** [comment]
Thanks - now I see the log entries from the composer. No idea why I did not look there.

PS: The German translation of "Show Content Messages" is weird: "Inhaltsmitteilungen"...

**Comment by spodermenpls** [comment]
@kkapsner This user's praise from thunderbird-mail.net's board is meant for you:
> Ich habe mir eben die von Ihnen neu angefertigten Smartquotes geladen und erfolgreich installiert. Großartig! Sie funktionieren noch besser als die vorherigen, d.h. sie funktionieren nun auch beim Zeilenwechsel automatisch korrekt. Große Freude und vielen lieben Dank für Ihre Arbeit, Zeit und erfolgreiche Programmierung!!!

**Comment by kkapsner** [comment]
Great that people like it.
