### ISSUE TITLE
duplicate curly & straight quotes appear

### ISSUE THREAD

**Issue by t4k** [spodermenpls/smartquotes#12]
_Environment:_
macOS 10.15.7
Thunderbird 78.11.0

_Language:_
English

When I type something like — I'm saying "hello" — into a mail message with Smart Quote active on the English setting, it gets transformed into — I’'m saying “"hello”" — with the curly + straight quote appearing at the same time.

![curly+straight-quotes](https://user-images.githubusercontent.com/415179/123316996-5e9d5a00-d4e2-11eb-9ab7-15c1918931f9.gif)

Halfway there!

I'm glad someone has taken up this extension!

**Comment by spodermenpls** [comment]
Thanks for bringing this up. I'm pretty certain this revolves around the usage of macOS, I've just checked it for myself and it works as intended on my Windows 10 setup, also with TB 78.11.0. Does someone in our team have a macOS system / VM at hand, to look into this? @kkapsner @theAlinP @jobisoft 

For obvious "viral" reasons I've been too occupied with more time critical things to be finishing up the begun work on this extension, but I'm hellbent on getting this show on the road in the next month or so, as a side note.

**Comment by kkapsner** [comment]
I have a VM running macOS and I can reproduce the problem. Not sure what causes it.

**Comment by kkapsner** [comment]
@jobisoft: I think it's a bug in Thunderbird under macOSX that `event.preventDefault()` is not working properly:
![image](https://user-images.githubusercontent.com/1105157/123475520-ca271a80-d5fb-11eb-9355-d347f6134df3.png)
defaultPrevented is set to `true` but the character is inserted.

**Comment by jobisoft** [comment]
Without a Mac this is difficult to investigate. Is this example working in Firefox on Mac?
https://www.mediaevent.de/javascript/onkeydown.html

Maybe we need to add event.stoppropagation()?

**Comment by kkapsner** [comment]
Don't have a Mac either... starting up my VM again...
The example under "Return in Formularen abfangen" works in Firefox on Mac.

> Maybe we need to add event.stoppropagation()?

Does not help.

**Comment by t4k** [comment]
It's so great knowing there is a team looking at this! I'm not sure how to help, but here are the results of typing into the mediaevent site:

![image](https://user-images.githubusercontent.com/415179/123484840-e015ea80-d5bd-11eb-90d7-7e9a3904a64a.png)
![image](https://user-images.githubusercontent.com/415179/123484923-fc198c00-d5bd-11eb-8eb1-481259b81e36.png)

Firefox 88.0
macOS 10.15.7

**Comment by spodermenpls** [comment]
@t4k Just to make sure, does the "Apply on selection" method still work, or does the duplicate issue occur with that way too?

**Comment by kkapsner** [comment]
"Apply to selection" works for me on my VM.

**Comment by t4k** [comment]
Apply to selection does not work completely for me.

I type: I'm saying "hello"
I select the phrase and choose Apply to selection
Only the double quotes around hello are changed: I'm saying “hello”
I try selecting just the word I'm and applying smart quotes: nothing changes
I try selecting just the apostrophe: an opening single quote is created, not a closing single quote

**Comment by spodermenpls** [comment]
@t4k Thanks for sharing, this confirms my observations I mentioned in the dedicated issue over here: https://github.com/spodermenpls/smartquotes/issues/13#issuecomment-868982941

**Comment by spodermenpls** [comment]
@kkapsner Do you think you might have something up your sleeve, concerning the current macOS incompatibility?

**Comment by kkapsner** [comment]
Oh - the little details... keydown is the wrong event... it has to be keypress.

**Comment by spodermenpls** [comment]
Excellent.

@t4k I just gave that fix a new release package, is it working now as intended on your end?

**Comment by t4k** [comment]
Yes! It is working as it should! Thank you everyone!
