### ISSUE TITLE
"Apply to selection" not working correctly with punctuation marks 

### ISSUE THREAD

**Issue by kkapsner** [spodermenpls/smartquotes#13]
If you select the sentence `I'm saying "Hello".` The last `"` is not converted.

**Comment by spodermenpls** [comment]
Good catch. 

On my end, the apostrophe between "I" and "m" doesn't get converted either, only in the "live mode". The apostrophe however does get converted, when using the German ruleset for "Apply to selection".

**Comment by kkapsner** [comment]
Created merge request that should fix this issue for the most common punctuation marks.

**Comment by spodermenpls** [comment]
@kkapsner Yes, that worked, and the fix looks a lot simpler than what I feared. The non-working _**"I'm"**_ conversion works now again, too, on my end.
