### ISSUE TITLE
Agree on a branch/merge/commit schema

### ISSUE THREAD

**Issue by kkapsner** [spodermenpls/smartquotes#3]
We need to have a good git schema so we do not interfere with each other. I'm open to anything.

Two suggestions from me:

1. the `main` branch is owned by @spodermenpls and only they should change it/merge into it
2. each of us should have an own dev branch

**Comment by theAlinP** [comment]
I agree with that.

**Comment by spodermenpls** [comment]
Yes, that's a good idea. Let's do it that way.
