### ISSUE TITLE
Create own website

### ISSUE THREAD

**Issue by kkapsner** [spodermenpls/smartquotes#5]
Should we create an own website? Or can we be part of smartquotes.info?

If we create an own one: where and how should we host?

**Comment by theAlinP** [comment]
The author of the original add-on and the owner of smartquotes.info did not respond to @spodermenpls's question yet, so I think that being part of it is out of the question. Let's leave the website for later.

**Comment by spodermenpls** [comment]
To be clear, the author of "Smart Quotes 0.1" is also the owner of smartquotes.info, and is indeed still totally unresponsive.

@kkapsner I don't really see the need for a separate website for this tool though, is there more to it than what can be explained in this repo and on a future addons.thunderbird.net site?

**Comment by kkapsner** [comment]
Hm... well we will probably not have alpha/beta/RC versions (the extension has no privacy/security relation) and it can be submitted to ATN so the tools in this repo and ATN can be sufficient.

OK - let's try without dedicated site. We can create one if we feel the need for it.
