### ISSUE TITLE
Coding environment

### ISSUE THREAD

**Issue by kkapsner** [spodermenpls/smartquotes#6]
Which coding environment do you use?

I use vscode, web-ext and nodejs.

I think it would be a good idea to have some commonly used scripts (like I have [here](https://github.com/kkapsner/CanvasBlocker/tree/master/.tools) and [here](https://github.com/kkapsner/keepassxc-mail/tree/master/.tools)) to streamline the workflow.

**Comment by jobisoft** [comment]
Just to point this out: If you use anything but plain vanilla javascript, getting your add-on reviewed for ATN will always take much much longer, as the reviewer has to clone your build process and has to verify your sources and your build.

**Comment by kkapsner** [comment]
Good to know - so if the discussion comes to JavaScript vs. TypeScript we have to keep that in mind.

**Comment by theAlinP** [comment]
I use the same coding environment. You can use any scripts you consider necessary.

**Comment by kkapsner** [comment]
I would use npm to handle any dev related dependencies (I don't think we need dependencies for the webExtension itself).
