### ISSUE TITLE
Agree on code style

### ISSUE THREAD

**Issue by kkapsner** [spodermenpls/smartquotes#7]
We need to agree on a code style and we should set up a linter to enforce it.

I use eslint and my preferences can be seen [here](https://github.com/kkapsner/CanvasBlocker/blob/master/.eslintrc.json) and [here](https://github.com/kkapsner/keepassxc-mail/blob/master/.eslintrc.json).

**Comment by theAlinP** [comment]
I use ESLint, too. If we're going to use vanilla JS, maybe we should disable JSX. I usually use 2-space indentation, but I'm OK with tabs. I don't think I will be able to contribute very often which means you should decide what indentation to use.

**Comment by kkapsner** [comment]
Actually I'm not sure why I have JSX enabled in the other ones...

> I usually use 2-space indentation, but I'm OK with tabs.

I'm the other way around. I usually use tabs (displayed with 4 spaces).

> I don't think I will be able to contribute very often which means you should decide what indentation to use.

@spodermenpls what is your preference?

**Comment by spodermenpls** [comment]
I personally prefer the "tabbed" style over "spaced", as well. Let's go with that.
